//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECommerceEntities : DbContext
    {
        public ECommerceEntities()
            : base("name=ECommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<AdminUser> AdminUser { get; set; }
        public virtual DbSet<AppUser> AppUser { get; set; }
        public virtual DbSet<AppUserMapAddress> AppUserMapAddress { get; set; }
        public virtual DbSet<AppUserMapWish> AppUserMapWish { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<County> County { get; set; }
        public virtual DbSet<DiscountKey> DiscountKey { get; set; }
        public virtual DbSet<Parameter> Parameter { get; set; }
        public virtual DbSet<ParameterType> ParameterType { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductMapComment> ProductMapComment { get; set; }
        public virtual DbSet<ProductMapImage> ProductMapImage { get; set; }
        public virtual DbSet<ProductMapProperty> ProductMapProperty { get; set; }
        public virtual DbSet<ProductMapRequiredFields> ProductMapRequiredFields { get; set; }
        public virtual DbSet<ProductMapShippers> ProductMapShippers { get; set; }
        public virtual DbSet<Shipper> Shipper { get; set; }
        public virtual DbSet<UserCart> UserCart { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
    }
}
